name: PR

on:
  pull_request:

permissions:
  contents: read
  id-token: write
  deployments: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: elastic/docs-builder@main
        with:
          strict: false
      - uses: elastic/docs-builder/actions/preview@feature/consumer-preview-action
        with:
          strict: false
