name: docs-build

on:
  pull_request: ~

jobs:
  preview:
    uses: elastic/docs-builder/.github/workflows/preview-build.yml@feature/optimize-preview
    with:
      continue-on-error: true
      strict: false
    permissions:
      contents: read
