name: docs

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  docs-preview:
    uses: elastic/docs-builder/.github/workflows/preview.yml@feature/consumer-preview-action
    permissions:
      contents: read
      id-token: write
      deployments: write
    with:
      strict: false
